### ISSUE TITLE
Backspaces are broken

### ISSUE THREAD

**Issue by gruelingpine185** [yeti0904/yterm#4]
At the moment, backspaces rely solely on the cursor position (this should actually be called caret see below). This is problematic because of these lines:

https://github.com/yeti0904/yterm/blob/539a52ce1b4b53dba1deea63128e05a8ad21f8f3/source/textScreen.c#L71-L78

This is because it doesn't account for the prompt length or any other potential default writable offset. That means that if I have a prompt 36 characters long (not including NULL terminator), the "cursor" position says I am at column 37. In theory, I should be able to press backspace that many times (minus 1) before I can't anymore because it will reset to 0. However, that isn't the case. I can't backspace through the prompt (which is good because I'm not supposed to be able to) [but/because] whenever I try to, backspaces begin to increment `cursor.x` in addition to writing printable characters that cannot be removed.
<img width="788" alt="emptyy_win" src="https://github.com/yeti0904/yterm/assets/66073333/2613b4fe-90dc-439b-8bb1-942c6f085d59">

<img width="832" alt="bug" src="https://github.com/yeti0904/yterm/assets/66073333/53962143-716e-4968-9486-683960141956">

This is crazy for 3 reasons:
1. I don't see the code that would cause a reversal unless somehow backspaces change character values and end up triggering the default case, which happens to be the only place in the codebase that increments `cursor.x`. https://github.com/yeti0904/yterm/blob/539a52ce1b4b53dba1deea63128e05a8ad21f8f3/source/textScreen.c#L79-L86

2. Where are these characters even coming from? Backspaces are non-printable
3. If I don't try to backspace through the prompt, backspaces work fine.
---

Carets are the actual blinking line or some other indicator for position in text. Cursors, however, are graphical and are associated with mouse actions. These typically can be your pointers, crosshairs, re-sizers, etc.

While I'm at it, what's your justification behind the types used throughout the code? For example, you make a cast to `size_t` from a `char` for the index of an array that is hardcoded to only be `uint8_t` max. There are several other instances that should be addressed.

**Comment by MESYETI** [comment]
the font that comes with yterm is a code page 437 font, which means pretty much any character is printable
a code page 437 table shows that those characters are character 7, which is the bell in the ASCII set
seems like it's the shell's way of telling the user they're back spacing at the shell prompt, so I just need to make a case for the bell in TextScreen_PutCharacter

**Comment by MESYETI** [comment]
fixed in a106c6e
